title: "自媒体创作指南"
url: "https://smlog.github.io"
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://smlog.github.io/"
footer_text: "Page design by 业余时间"

sass:
  style: compressed
  sass_dir: _sass

nav:
  - name: "首页"
    link: "/"
  - name: "Resume"
    link: "resume.pdf"
  - name: "Contact"
    link: "contact"
