title: "my foot"
url: "https://smlog.github.io"
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://cctranslate.github.io/"
footer_text: "Page design by cc 翻译"

sass:
  style: compressed
  sass_dir: _sass

nav:
  - name: "理论"
    link: "/#theory"
  - name: "坚持"
    link: "/#keep"
